### PR TITLE
BSSQLiteDatabase implementation + integration tests for operations

### LINKED ISSUE #55: Create BambooStorageSQLiteDatabase implementation

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #55 

@nikitin-da PTAL

Also, I refactored `DeleteResult` and added some methods to query results

### CODE REVIEW

**Comment by nikitin-da** [comment]
Failed =(

**Comment by artem-zinnatullin** [comment]
I see, in current `master` there is `rawQuery` support, I'll update PR now

**Comment by artem-zinnatullin** [comment]
PR updated, I need to sleep..

**Comment by nikitin-da** [comment]
sleep for wimps!

**Comment by artem-zinnatullin** [comment]
wimp want to sleep..

**Pull request merged**
